import type { Product, Category, Store } from "@/types";

export const mockStore: Store = {
  id: "store-1",
  owner_id: "user-1",
  name: "Apple Store Bogotá",
  slug: "apple-store-bogota",
  description: "Distribuidor autorizado de iPhones en Bogotá",
  logo_url: null,
  banner_url: null,
  rating: 4.8,
  total_sales: 1250,
  verified: true,
  active: true,
  created_at: "2024-01-01",
  updated_at: "2024-01-01",
};

export const mockStore2: Store = {
  id: "store-2",
  owner_id: "user-2",
  name: "TechMovil CO",
  slug: "techmovil-co",
  description: "Los mejores iPhones usados con garantía",
  logo_url: null,
  banner_url: null,
  rating: 4.6,
  total_sales: 830,
  verified: true,
  active: true,
  created_at: "2024-02-01",
  updated_at: "2024-02-01",
};

export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    description: "Lo último de Apple con chip A18 Pro",
    image_url: null,
    order: 1,
  },
  {
    id: "cat-2",
    name: "iPhone 16 Pro",
    slug: "iphone-16-pro",
    description: "Potencia profesional en tu bolsillo",
    image_url: null,
    order: 2,
  },
  {
    id: "cat-3",
    name: "iPhone 15 Pro Max",
    slug: "iphone-15-pro-max",
    description: "Titanio y rendimiento excepcional",
    image_url: null,
    order: 3,
  },
  {
    id: "cat-4",
    name: "iPhone 15",
    slug: "iphone-15",
    description: "Dynamic Island para todos",
    image_url: null,
    order: 4,
  },
  {
    id: "cat-5",
    name: "iPhone 14",
    slug: "iphone-14",
    description: "Calidad premium a mejor precio",
    image_url: null,
    order: 5,
  },
  {
    id: "cat-6",
    name: "iPhone 13",
    slug: "iphone-13",
    description: "Rendimiento probado y confiable",
    image_url: null,
    order: 6,
  },
];

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    store_id: "store-1",
    category_id: "cat-1",
    name: "iPhone 16 Pro Max 256GB Titanio Natural",
    slug: "iphone-16-pro-max-256gb-titanio-natural",
    description: "iPhone 16 Pro Max completamente nuevo, sellado en caja.",
    model: "iPhone 16 Pro Max",
    condition: "nuevo",
    storage: "256GB",
    color: "Titanio Natural",
    price: 5899000,
    compare_at_price: 6299000,
    stock: 5,
    images: [],
    featured: true,
    active: true,
    created_at: "2024-10-01",
    updated_at: "2024-10-01",
    store: mockStore,
  },
  {
    id: "prod-2",
    store_id: "store-1",
    category_id: "cat-2",
    name: "iPhone 16 Pro 128GB Titanio Negro",
    slug: "iphone-16-pro-128gb-titanio-negro",
    description: "iPhone 16 Pro nuevo, sellado. Garantía Apple de 1 año.",
    model: "iPhone 16 Pro",
    condition: "nuevo",
    storage: "128GB",
    color: "Titanio Negro",
    price: 4799000,
    compare_at_price: 5199000,
    stock: 8,
    images: [],
    featured: true,
    active: true,
    created_at: "2024-10-01",
    updated_at: "2024-10-01",
    store: mockStore,
  },
  {
    id: "prod-3",
    store_id: "store-2",
    category_id: "cat-3",
    name: "iPhone 15 Pro Max 256GB Titanio Azul",
    slug: "iphone-15-pro-max-256gb-titanio-azul",
    description: "Como nuevo, sin rayones. Batería al 98%.",
    model: "iPhone 15 Pro Max",
    condition: "como_nuevo",
    storage: "256GB",
    color: "Titanio Azul",
    price: 4299000,
    compare_at_price: 5099000,
    stock: 3,
    images: [],
    featured: true,
    active: true,
    created_at: "2024-09-15",
    updated_at: "2024-09-15",
    store: mockStore2,
  },
  {
    id: "prod-4",
    store_id: "store-2",
    category_id: "cat-4",
    name: "iPhone 15 128GB Negro",
    slug: "iphone-15-128gb-negro",
    description: "En excelente estado. Incluye cargador y estuche.",
    model: "iPhone 15",
    condition: "excelente",
    storage: "128GB",
    color: "Negro",
    price: 2899000,
    compare_at_price: 3499000,
    stock: 6,
    images: [],
    featured: false,
    active: true,
    created_at: "2024-08-20",
    updated_at: "2024-08-20",
    store: mockStore2,
  },
  {
    id: "prod-5",
    store_id: "store-1",
    category_id: "cat-5",
    name: "iPhone 14 Pro 256GB Morado Oscuro",
    slug: "iphone-14-pro-256gb-morado-oscuro",
    description: "Nuevo sellado. Color exclusivo morado oscuro.",
    model: "iPhone 14 Pro",
    condition: "nuevo",
    storage: "256GB",
    color: "Morado Oscuro",
    price: 3599000,
    compare_at_price: 3999000,
    stock: 4,
    images: [],
    featured: true,
    active: true,
    created_at: "2024-07-10",
    updated_at: "2024-07-10",
    store: mockStore,
  },
  {
    id: "prod-6",
    store_id: "store-2",
    category_id: "cat-6",
    name: "iPhone 13 128GB Azul",
    slug: "iphone-13-128gb-azul",
    description: "Buen estado general. Batería al 89%. Funciona perfecto.",
    model: "iPhone 13",
    condition: "bueno",
    storage: "128GB",
    color: "Azul",
    price: 1799000,
    compare_at_price: 2299000,
    stock: 10,
    images: [],
    featured: false,
    active: true,
    created_at: "2024-06-05",
    updated_at: "2024-06-05",
    store: mockStore2,
  },
  {
    id: "prod-7",
    store_id: "store-1",
    category_id: "cat-1",
    name: "iPhone 16 Pro Max 512GB Titanio Blanco",
    slug: "iphone-16-pro-max-512gb-titanio-blanco",
    description: "Máximo almacenamiento. Nuevo, sellado en caja original.",
    model: "iPhone 16 Pro Max",
    condition: "nuevo",
    storage: "512GB",
    color: "Titanio Blanco",
    price: 6999000,
    compare_at_price: 7499000,
    stock: 2,
    images: [],
    featured: true,
    active: true,
    created_at: "2024-10-05",
    updated_at: "2024-10-05",
    store: mockStore,
  },
  {
    id: "prod-8",
    store_id: "store-2",
    category_id: "cat-4",
    name: "iPhone 15 Plus 256GB Rosa",
    slug: "iphone-15-plus-256gb-rosa",
    description: "Como nuevo, usado solo 2 meses. Batería al 100%.",
    model: "iPhone 15 Plus",
    condition: "como_nuevo",
    storage: "256GB",
    color: "Rosa",
    price: 3399000,
    compare_at_price: 3999000,
    stock: 1,
    images: [],
    featured: false,
    active: true,
    created_at: "2024-09-01",
    updated_at: "2024-09-01",
    store: mockStore2,
  },
];
